-- init-slave.sql
#MASTER
SET GLOBAL server_id=1;

#REPLICA
RESET REPLICA ALL;
SET GLOBAL server_id=2;
CHANGE MASTER TO
    MASTER_HOST='mysql-master',
    MASTER_USER='repl_user',
    MASTER_PASSWORD='amir123456789',
    MASTER_LOG_FILE='SHOW IN MASTER STATUS',
    MASTER_LOG_POS=SHOW IN MANSTER STATUS;


